// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVFf6e5wYQzp__xStamlsl3SZtagJt4gM',
    appId: '1:371772887866:web:49fc57e8b1038b9b943603',
    messagingSenderId: '371772887866',
    projectId: 'luedke-cb8db',
    authDomain: 'luedke-cb8db.firebaseapp.com',
    storageBucket: 'luedke-cb8db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhryl3fHIEOAHlyLqRGhu24jFxeEju8qc',
    appId: '1:371772887866:android:427506dc02127c12943603',
    messagingSenderId: '371772887866',
    projectId: 'luedke-cb8db',
    storageBucket: 'luedke-cb8db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3-6sLHU5bRZ6FKJYO95yySaiaMfcfG0',
    appId: '1:371772887866:ios:65bf75756d54ebba943603',
    messagingSenderId: '371772887866',
    projectId: 'luedke-cb8db',
    storageBucket: 'luedke-cb8db.appspot.com',
    iosBundleId: 'com.arquitetura.luedke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVFf6e5wYQzp__xStamlsl3SZtagJt4gM',
    appId: '1:371772887866:web:e5ada2d6326895a3943603',
    messagingSenderId: '371772887866',
    projectId: 'luedke-cb8db',
    authDomain: 'luedke-cb8db.firebaseapp.com',
    storageBucket: 'luedke-cb8db.appspot.com',
  );

}